"use strict";
exports.__esModule = true;
var am;
am = "arnab";
var Color;
(function (Color) {
    Color[Color["Red"] = 0] = "Red";
    Color[Color["Green"] = 1] = "Green";
    Color[Color["Brown"] = 2] = "Brown";
    Color[Color["White"] = 3] = "White";
})(Color || (Color = {}));
;
var c = Color.Brown;
console.log("letus see what is there in the enum {{c}}");
var random;
random = true;
console.log(random);
random = "hello";
console.log(random);
random = [4, 94, 84, 25, 75, 73, 95, 1, 74, 22, 55, 33, 99, 0, 3, 860, 24];
console.log(random);
var list2 = [3, 7, 8, 4, 9, 2, 90, 43];
console.log(list2);
console.log(am);
